- name: ansible-playbook-debian-server
  hosts: localhost,
  become: yes
  become_method: su
  become_flags: "-"
  roles:
    - ansible-role-nfs
  tasks:
    - name: Ensure data partition is mounted
      ansible.posix.mount:
        path: /data
        src: UUID=cf815afe-91db-4301-9108-2d907a93bec0
        fstype: ext4
        opts: defaults
        state: mounted
    - import_tasks: tasks/restore.yml
    - name: Ensure .ssh directory exists
      file:
        path: /home/fekr/.ssh
        state: directory
        owner: fekr
        group: fekr
        mode: '0700'
    - name: Copy ssh authorized_keys from Github
      shell:
        cmd: wget -O /home/fekr/.ssh/authorized_keys https://gist.githubusercontent.com/felixkroemer/c628ea1015e56f7d2f42f0c92c67ec92/raw
    - import_tasks: tasks/authorized-keys-sync.yml
    - import_tasks: tasks/avahi.yml
  vars_files:
    - vault.yml
  vars:
    nfs_exports: [ "/data    *(rw,sync)" ]
  vars_prompt:
    - name: duplicity_b2_url
      prompt: "B2 backup URL (b2://DUPLICITY_API_KEY_ID:DUPLICITY_API_KEY@BUCKET_NAME)? Leave empty to skip restore"
      private: no