- name: ansible-playbook-debian-server
  hosts: localhost,
  become: yes
  become_method: su
  become_flags: "-"
  roles:
    - ansible-role-nfs
    - drop-catcher
  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: /home/fekr/.ssh
        state: directory
        owner: fekr
        group: fekr
        mode: '0700'
    - name: Copy ssh authorized_keys from Github
      shell:
        cmd: wget -O /home/fekr/.ssh/authorized_keys https://gist.githubusercontent.com/felixkroemer/c628ea1015e56f7d2f42f0c92c67ec92/raw
  vars_files:
    - vault.yml
  vars:
    nfs_exports: [ "/data    *(rw,sync)" ]